#!/usr/bin/env bash

if [[ "$MSYSTEM" == "MINGW64" ]]; then
    # Running in Git Bash on Windows.

    set -x
    winpty python3 -m minidocker.py run \
        -e GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID} \
        -v /$(dirname ${GCP_APP_CREDENTIALS}):/tmp/gcp_creds \
        -e GOOGLE_APPLICATION_CREDENTIALS=//tmp/gcp_creds/$(basename ${GCP_APP_CREDENTIALS}) \
        cloudly:dev
else
    python3 -m minidocker.py run \
        -e GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID} \
        -v $(dirname ${GCP_APP_CREDENTIALS}):/tmp/gcp_creds \
        -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp_creds/$(basename ${GCP_APP_CREDENTIALS}) \
        cloudly:dev
fi
